---
- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone Remote Git Repository
  git:
    repo: https://github.com/AmadouKa-Dev/k3s-deploy.git
    dest: /home/ubuntu/gestion-depense-deploy

# git config --global --add safe.directory /home/ubuntu/gestion-depense-deploy Ã  ajouter